Factory/Models/Engineer.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
    public class Engineer
    {
        public int EngineerId { get; set; }
        [Required(ErrorMessage = "Engineer's Name required")]
        public string Name { get; set; }
        public List<EngineerMachine> JoinEntities { get; set; }
    }

}

Factory/Models/EngineerMachines.cs
namespace Factory.Models
{
    public class EngineerMachine
    {
        public int EngineerMachineId { get; set; }
        public int EngineerId { get; set; }
        public Engineer Engineer { get; set; }
        public int MachineId { get; set; }
        public Machine Machine { get; set; }
    }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
    public class FactoryContext : DbContext
    {
        public DbSet<Engineer> Engineers { get; set; }
        public DbSet<Machine> Machines { get; set; }
        public DbSet<EngineerMachine> EngineerMachine { get; set; }

        public FactoryContext(DbContextOptions options) : base(options) { }
    }
}

Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
    public class Machine
    {
        public int MachineId { get; set; }
        [Required(ErrorMessage = "Machine's Name required")]
        public string Name { get; set; }
        public List<EngineerMachine> JoinEntities { get; set; }
    }
}

Factory/Controllers/EngineerController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Linq;

namespace Factory.Controllers
{
    public class EngineersController : Controller
    {
        private readonly FactoryContext _db;

        public EngineersController(FactoryContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Engineers.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Engineer engineer)
        {
            if (!ModelState.IsValid)
            {
                return View(engineer);
            }
            else
            {
                _db.Engineers.Add(engineer);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Details(int id)
        {
            Engineer thisEngineer = _db.Engineers
                .Include(engineer => engineer.JoinEntities)
                .ThenInclude(join => join.Machine)
                .FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }

        public ActionResult AddMachine(int id)
        {
            Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
            ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
            return View(thisEngineer);
        }

        [HttpPost]
        public ActionResult AddMachine(Engineer engineer, int MachineId)
        {
#nullable enable
            EngineerMachine? joinEntity = _db.EngineerMachine.FirstOrDefault(join => join.EngineerId == engineer.EngineerId && join.MachineId == MachineId);
#nullable disable
            if (joinEntity == null && MachineId != 0)
            {
                _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = engineer.EngineerId, MachineId = MachineId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = engineer.EngineerId });
        }

        public ActionResult Edit(int id)
        {
            Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
            ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
            return View(thisEngineer);
        }

        [HttpPost]
        public ActionResult Edit(Engineer engineer)
        {
            if (!ModelState.IsValid)
            {
                return View(engineer);
            }
            else
            {
                _db.Entry(engineer).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = engineer.EngineerId });
            }
        }

        public ActionResult Delete(int id)
        {
            Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
            _db.Engineers.Remove(thisEngineer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }

}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Facory.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }

    }
}

Factory/Controllers/MachineController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Linq;

namespace Factory.Controllers
{
    public class MachinesController : Controller
    {
        private readonly FactoryContext _db;

        public MachinesController(FactoryContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Machines.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Machine machine)
        {
            if (!ModelState.IsValid)
            {
                return View(machine);
            }
            else
            {
                _db.Machines.Add(machine);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Details(int id)
        {
            Machine thisMachine = _db.Machines
                .Include(machine => machine.JoinEntities)
                .ThenInclude(join => join.Engineer)
                .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }

        public ActionResult AddEngineer(int id)
        {
            Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
            ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
            return View(thisMachine);
        }

        [HttpPost]
        public ActionResult AddEngineer(Machine machine, int EngineerId)
        {
#nullable enable
            EngineerMachine? joinEntity = _db.EngineerMachine.FirstOrDefault(join => join.MachineId == machine.MachineId && join.EngineerId == EngineerId);
#nullable disable
            if (joinEntity == null && EngineerId != 0)
            {
                _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = machine.MachineId });
        }

        public ActionResult Edit(int id)
        {
            Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
            ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
            return View(thisMachine);
        }

        [HttpPost]
        public ActionResult Edit(Machine machine)
        {
            if (!ModelState.IsValid)
            {
                return View(machine);
            }
            else
            {
                _db.Entry(machine).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = machine.MachineId });
            }
        }

        public ActionResult Delete(int id)
        {
            Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
            _db.Machines.Remove(thisMachine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }

}

Factory/Views/Engineers/AddMachine.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add an assigned Machine</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)
    @Html.Label("Select an Machine")
    @Html.DropDownList("MachineId")
    <br>

    <input id="form-button" type="submit" value="Save" />
}

<div id="nav-links">
    <p>@Html.ActionLink($"{Model.Name}'s Details", "Details", "Engineers")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    <p>@Html.ActionLink("Engineers", "Index", "Engineers")</p>
</div>

Factory/Views/Engineers/Create.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Add Engineer</h3>
@using (Html.BeginForm()) 
{
    @Html.LabelFor(model => model.Name)
    <br>
    @Html.TextBoxFor(model => model.Name)
    <br>

    <input id="form-button" type="submit" value="Add" />

    <p class="invalid-input">@Html.ValidationMessageFor(model => model.Name)</p>
}

<div id="nav-links">
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

Factory/Views/Engineers/Delete.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Add Engineer</h3>

<h4>Are you sure you want to delete this engineer?</h4>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

<div id="nav-links">
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

Factory/Views/Engineers/Details.cshtml
@{
    Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer


<div id="object-deets">
    <h1 class="display-name">@Html.DisplayFor(model => model.Name)<h1>

    @if (@Model.JoinEntities.Count == 0)
            {
                    <h3>This engineer is not liscensed to repair any machines.</h3>
            }
            else
            {
                    <h3>Machines:</h3>
                    <ul class="engineer-machine-link">
                    @foreach (var machine in Model.JoinEntities)
                    {
                                        <li class="list-margins">@Html.ActionLink($"{machine.Machine.Name}", "Details", "Machines", new {id = machine.MachineId})</li>
                    }
                    </ul>
            }
</div>


    <p class="add-to-list">@Html.ActionLink("Add Machine Here", "AddMachine", "Engineers", new {id = Model.EngineerId})</p>

<div id="nav-links">

    <p>@Html.ActionLink("Engineers", "Index", "Engineers")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    <p>@Html.ActionLink("Edit Engineer", "Edit", "Engineers", new { id = Model.EngineerId })</p>
    <p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Edit Engineer Details</h3>
@using (Html.BeginForm()) 
{

    @Html.HiddenFor(model => model.EngineerId)
    <br>

    @Html.LabelFor(model => model.Name)
    <br>
    @Html.TextBoxFor(model => model.Name)
    <br>

    <input type="submit" value="Save" />

    <p class="invalid-input">@Html.ValidationMessageFor(model => model.Name)</p>
}

<div id="nav-links">
    <p>@Html.ActionLink("Engineers", "Index", "Engineers")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    <p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
</div>

Factory/Views/Engineers/Index.cshtml
@{
    Layout = "_Layout";
} @using Factory.Models

<h1>Engineers</h1>

@if (@Model.Count == 0)
{
    <div id="empty-value-div">
    <h3>There are currently no engineers.</h3>
    <p>
        Add an Engineer
        <span id="inner-nav-link">@Html.ActionLink("HERE", "Create")</span> in
        order to Add Engineers.
    </p>
</div>

    <div id="nav-links">
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

}
else
{
    <div id="nav-links">
    <p>@Html.ActionLink("Add Engineer", "Create", "Engineers")</p>
    <p>@Html.ActionLink("Add Machine", "Create", "Machines")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>
}
<ul class="engineer-machine-link">
    @foreach (Engineer engineer in Model)
    {
        <li>
            @Html.ActionLink($"{engineer.Name}", "Details", "Engineers", new {id =
        engineer.EngineerId})
        </li>
    }
</ul>

Factory/Views/Home/Index.cshtml
@{

    Layout = "_Layout";

} @using Factory.Models;

<h1 id="home-page-title">Dr. Sillystringz Maintenance Manager</h1>

<div id="home-page-overview">
    <p>For your Maintenance tracking needs!</p>
    <p>
        This Maintenance Management System helps manage Engineer and Machine
        information to help keep operations running smoothly.
    </p>
    <p id="home-page-overview-disclaimer">
        Use the links at the bottom of this page to navigate to the Engineer
        List and Machine List pages.
    </p>
</div>

<div id="nav-links">
    <p>@Html.ActionLink("Engineers", "Index", "Engineers")</p>
    <p>@Html.ActionLink("Machines", "Index", "Machines")</p>
</div>

Factory/Views/Machines/AddEngineer.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a licensed Engineer</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)
    @Html.Label("Select an Engineer")
    @Html.DropDownList("EngineerId")
    <br>

    <input id="button" type="submit" value="Save" />
}

<div id="nav-links">
    <p>@Html.ActionLink($"{Model.Name} Details", "Details", "Machines")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    <p>@Html.ActionLink("Machines", "Index", "Machines")</p>
</div>

Factory/Views/Machines/Create.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Add Machine</h3>
@using (Html.BeginForm()) 
{
    @Html.LabelFor(model => model.Name)
    <br>
    @Html.TextBoxFor(model => model.Name)
    <br>

    <input id="form-button" type="submit" value="Add" />

    <p class="invalid-input">@Html.ValidationMessageFor(model => model.Name)</p>
}

<div id="nav-links">
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

Factory/Views/Machines/Delete.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Delete Machine</h3>

<h4>Are you sure you want to delete this machine?</h4>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}

Factory/Views/Machines/Details.cshtml
@{
    Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h1 class="display-name">@Model.Name</h1>

@if (@Model.JoinEntities.Count == 0)
{
    <p>This machine is not assigned to any licensed engineers.</p>
}
else
{
    <h4>Engineers with a license for this machine:</h4>
    <ul class="engineer-machine-link">
        @foreach (var engineer in Model.JoinEntities)
        {
            <li class="list-margins">@Html.ActionLink($"{engineer.Engineer.Name}", "Details", "Engineers", new {id = engineer.EngineerId})</li>
        }
    </ul>
}


    <p class="add-to-list">@Html.ActionLink("Add Engineer Here", "AddEngineer", "Machines", new {id = Model.MachineId})</p>

<div id="nav-links">
    <p>@Html.ActionLink("Machines", "Index", "Machines")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    <p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
    <p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
</div>

Factory/Views/Machines/Edit.cshtml
@{
    Layout = "_Layout";
} 

@model Factory.Models.Machine

<h4>Update Machine Details</h4>

@using(Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)
    <br>

    @Html.LabelFor(model => model.Name)
    <br>
    @Html.EditorFor(model => model.Name)
    <br>

    @Html.Label("Select Engineer")
    @Html.DropDownList("EngineerId")
    <br>

    <input type="submit" value="Save" />
}

<div id="nav-links">
    <p>@Html.ActionLink("Machines", "Index", "Machines")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    <p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
    
</div>

Factory/Views/Machines/Index.cshtml
@{
    Layout = "_Layout";
} @using Factory.Models

<h1>Machines</h1>

@if (@Model.Count == 0)
{
    <div id="empty-value-div">
    <h3>There are no currently no Machines.</h3>
    <p>
        Add a Machine
        <span id="inner-nav-link">@Html.ActionLink("HERE", "Create")</span> in
        order to Add Machines.
    </p>
</div>

    <div id="nav-links">
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>
}
else
{
    <div id="nav-links">
    <p>@Html.ActionLink("Add Machine", "Create", "Machines")</p>
    <p>@Html.ActionLink("Home", "Index", "Home")</p>
    <p>@Html.ActionLink("Add Engineer", "Create", "Engineers")</p>
</div>
}

<ul class="engineer-machine-link">
    @foreach (Machine machine in Model)
    {
        <li class="list-margins">
            @Html.ActionLink($"{machine.Name}", "Details", "Machines", new {id =
        machine.MachineId})
        </li>
    }
</ul>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Factory Management</title>
        <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
        crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/styles.css">
    </head>
    <body>
        @RenderBody()
        @* @await Html.PartialAsync("Footer") *@
    </body>
</html>